name: Publish Package to npmjs

on:
  release:
    types: [created]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24.11.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish --access public