name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test