name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test